apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: ghcr.io/hagzag/wod:latest
        name: worker
        ports:
        - name: http
          containerPort: 8000
        command: ["poetry", "run", "uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "8080"]
        resources: {}
